spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: use_your_own_mysql
    password: use_your_own_mysql
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
